(()=>{
  const SHARED_DEVICE_ID='1f5fed11-afc5-4b9b-9a14-785950290a3d';
  const originalFetch=window.fetch.bind(window);
  window.fetch=(input,init={})=>{
    const url=typeof input==='string'?input:(input&&input.url)||'';
    if(/\/(watch-rules|scan-now|scan-latest)(?:\?|$)/.test(url)){
      const headers=new Headers(init.headers||(input instanceof Request?input.headers:undefined));
      headers.set('x-device-id',SHARED_DEVICE_ID);init={...init,headers};
    }
    return originalFetch(input,init);
  };
  const style=document.createElement('style');style.textContent=`
    :root{--purple:#9d8cff;--purple-strong:#7566f6;--orange:#ff8a32;--orange-strong:#f56f14}
    .hero h1{margin-bottom:5px !important;color:var(--orange) !important}.hero>p{margin-top:4px !important;margin-bottom:14px !important}.hero b{color:var(--purple) !important}
    .matchImages:not(.one){grid-template-columns:repeat(2,minmax(0,1fr)) !important;gap:2px !important;overflow:hidden}.matchImages:not(.one) img,.matchImages.one img{width:100% !important;height:auto !important;aspect-ratio:16/9;object-fit:cover !important;object-position:center !important;transform:none !important;display:block}.vehicleFilterTitle{font-size:13px !important}.vehicleFilterMeta{font-size:10.5px !important}
    #statusActions{display:flex;align-items:center;gap:8px;margin-top:10px;flex-wrap:wrap}.hero #statusActions .status{margin-top:0 !important;height:40px;border-color:rgba(117,102,246,.45) !important}.hero #statusActions .status::before{background:var(--purple) !important;box-shadow:0 0 10px rgba(157,140,255,.45) !important}.hero #allCarsLink{display:inline-flex;align-items:center;justify-content:center;gap:6px;margin:0 !important;height:40px;padding:0 13px;border:1px solid var(--purple-strong);border-radius:999px;background:rgba(117,102,246,.18);color:#dedaff;text-decoration:none;font-size:12px;font-weight:750;line-height:1;white-space:nowrap;box-shadow:inset 0 0 0 1px rgba(157,140,255,.12),0 0 20px rgba(117,102,246,.10)}#allCarsLink svg{width:14px;height:14px;display:block;flex:none;color:#c8c1ff}#allCarsLink:active{background:rgba(117,102,246,.28);color:#fff;border-color:#aa9fff}
    .shell>section.card:nth-of-type(1)>.sectionHead,.shell>section.card:nth-of-type(2)>.sectionHead,.shell>section.card:nth-of-type(3)>.sectionHead{padding-bottom:12px;border-bottom:1px solid #252c36;margin-bottom:4px}.shell>section.card:nth-of-type(1)>.sectionHead h2,.shell>section.card:nth-of-type(2)>.sectionHead h2,.shell>section.card:nth-of-type(3)>.sectionHead h2{color:var(--orange) !important}
    .addBtn,.notifyPrimary{background:var(--purple-strong) !important;color:#fff !important}.refreshBtn{border-color:rgba(157,140,255,.55) !important;color:#c8c1ff !important}.refreshBtn:active{background:rgba(117,102,246,.13) !important}.vehicleFilter.active{background:rgba(117,102,246,.18) !important;border-color:var(--purple-strong) !important;box-shadow:inset 0 0 0 1px rgba(157,140,255,.15) !important}.vehicleFilter.active .vehicleFilterMeta{color:#b8afff !important}.actionGroup .edit{color:#bcb4ff !important}.actionGroup .toggle{background:rgba(117,102,246,.20) !important;color:#bcb4ff !important;border-color:rgba(117,102,246,.32) !important}
    #scanSummary{line-height:1.45 !important;margin-top:6px}.vehicleFilters{padding-top:10px !important;padding-bottom:4px !important;column-gap:11px !important;row-gap:10px !important}.vehicleFilter{width:calc(100% - 4px) !important;justify-self:center}.filterHint{margin-top:7px !important}.matchList{margin-top:12px !important}#rules{margin-top:2px}.rule{padding:13px 0 !important}.rule p{margin-top:5px !important}.rule:first-child{padding-top:9px !important}.rule:last-child{padding-bottom:6px !important}
    #themeToggle{position:fixed;z-index:10020;top:max(14px,env(safe-area-inset-top));right:14px;width:42px;height:42px;border-radius:999px;border:1px solid rgba(157,140,255,.45);background:rgba(17,22,30,.88);color:var(--purple);display:flex;align-items:center;justify-content:center;padding:0;box-shadow:0 8px 24px rgba(0,0,0,.22);backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px);cursor:pointer}#themeToggle svg{width:19px;height:19px}#themeToggle:active{transform:scale(.96)}
    #ruleModalBackdrop{display:none;position:fixed;inset:0;z-index:9998;background:rgba(3,6,10,.72);backdrop-filter:blur(7px);-webkit-backdrop-filter:blur(7px)}#ruleModalBackdrop.open{display:block}#formCard.formCard{position:fixed !important;z-index:9999 !important;left:50% !important;top:50% !important;transform:translate(-50%,-50%) scale(.97);width:min(620px,calc(100vw - 28px)) !important;max-height:calc(100dvh - 40px);overflow-y:auto;margin:0 !important;padding:22px !important;border-radius:22px !important;box-shadow:0 24px 80px rgba(0,0,0,.55);opacity:0;visibility:hidden;display:block !important;pointer-events:none;transition:opacity .18s ease,transform .18s ease,visibility .18s}#formCard.formCard.open{opacity:1;visibility:visible;pointer-events:auto;transform:translate(-50%,-50%) scale(1)}body.rule-modal-open{overflow:hidden}
    body.light-theme{background:#f7f5ff;color:#17131f}body.light-theme .hero h1{color:var(--orange-strong) !important}body.light-theme .hero p{color:#6f6879}body.light-theme .card{background:#fff;border-color:#e5e0ef;box-shadow:0 4px 18px rgba(54,38,82,.05)}body.light-theme .sectionHead h2{color:var(--orange-strong) !important}body.light-theme .count,body.light-theme .hint,body.light-theme .filterHint,body.light-theme .notifyMeta{color:#827a8e}body.light-theme .status{background:#fff;border-color:#c9c0f7 !important;color:#51495c}body.light-theme #allCarsLink{background:#f0edff;border-color:#9487f4;color:#6256c8;box-shadow:none}body.light-theme #allCarsLink svg{color:#7566f6}body.light-theme .rule{border-color:#e8e2ee}body.light-theme .rule strong{color:#201a27}body.light-theme .rule p{color:#777080}body.light-theme .actionGroup{background:#faf8fc;border-color:#e2dce9}body.light-theme .actionGroup button{border-color:#e2dce9;color:#6f6879}body.light-theme .actionGroup .toggle{background:#f0edff !important;color:#6256c8 !important;border-color:#d5cef9 !important}body.light-theme .actionGroup .edit{color:#7566f6 !important}body.light-theme .vehicleFilter{background:#faf8fc;border-color:#e2dce9;color:#6f6879}body.light-theme .vehicleFilterTitle{color:#2a2332}body.light-theme .vehicleFilterMeta{color:#91899c}body.light-theme .vehicleFilter.active{background:#f0edff !important;border-color:#8f82f0 !important;color:#493eb0;box-shadow:inset 0 0 0 1px rgba(117,102,246,.10) !important}body.light-theme .vehicleFilter.active .vehicleFilterMeta{color:#7566f6 !important}body.light-theme .scanSummary{color:#6f6879}body.light-theme .matchCard{background:#fff;border-color:#e5e0eb}body.light-theme .matchBody{background:#fff}body.light-theme .matchTitle{color:#211a29}body.light-theme .matchIndex{color:#958d9f}body.light-theme .metaLabel{color:#958d9f}body.light-theme .metaValue{color:#4a4352}body.light-theme .metaItem.price .metaValue{color:#17131f}body.light-theme .refreshBtn{background:#f0edff !important;border-color:#a99ff3 !important;color:#6256c8 !important}body.light-theme .addBtn,body.light-theme .notifyPrimary{background:var(--purple-strong) !important;color:#fff !important}body.light-theme footer{color:#a29aa9}body.light-theme .shell>section.card:nth-of-type(1)>.sectionHead,body.light-theme .shell>section.card:nth-of-type(2)>.sectionHead,body.light-theme .shell>section.card:nth-of-type(3)>.sectionHead{border-color:#e8e2ee}body.light-theme input,body.light-theme select{background:#fff;color:#17131f;border-color:#dfd8e7}body.light-theme label{color:#6f6879}body.light-theme .secondary{background:#f1edf5;color:#5d5566}body.light-theme #formCard.formCard{background:#fff;box-shadow:0 24px 80px rgba(54,38,82,.20)}body.light-theme #themeToggle{background:rgba(255,255,255,.94);border-color:#c9c0f7;color:var(--purple-strong);box-shadow:0 6px 20px rgba(54,38,82,.10)}body.light-theme #ruleModalBackdrop{background:rgba(51,42,61,.28)}
    @media(max-width:520px){.hero h1{margin-bottom:4px !important}.hero>p{margin-top:3px !important;margin-bottom:12px !important}.vehicleFilterTitle{font-size:12.5px !important}.vehicleFilterMeta{font-size:10px !important}#statusActions{gap:6px}.hero #allCarsLink{height:38px;padding:0 12px;font-size:11.5px}.hero #statusActions .status{height:38px}.shell>section.card:nth-of-type(1)>.sectionHead,.shell>section.card:nth-of-type(2)>.sectionHead,.shell>section.card:nth-of-type(3)>.sectionHead{padding-bottom:10px;margin-bottom:3px}#scanSummary{margin-top:5px}.vehicleFilters{padding-top:8px !important;padding-bottom:4px !important;column-gap:9px !important;row-gap:9px !important}.vehicleFilter{width:calc(100% - 3px) !important}.filterHint{margin-top:6px !important}.matchList{margin-top:11px !important}#rules{margin-top:1px}.rule{padding:12px 0 !important}.rule:first-child{padding-top:8px !important}.rule:last-child{padding-bottom:4px !important}#themeToggle{width:40px;height:40px;right:12px;top:max(10px,env(safe-area-inset-top))}#formCard.formCard{top:auto !important;bottom:12px !important;transform:translateX(-50%) translateY(18px);width:calc(100vw - 20px) !important;max-height:calc(100dvh - 32px);border-radius:22px !important;padding:20px !important}#formCard.formCard.open{transform:translateX(-50%) translateY(0)}}`;
  document.head.appendChild(style);
  window.addEventListener('DOMContentLoaded',()=>{
    const form=document.getElementById('formCard');const heroCopy=document.querySelector('.hero>p');if(heroCopy)heroCopy.textContent='关注想买的二手车，达到心理价位时提醒。';document.getElementById('sharedHint')?.remove();
    const sun='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"><circle cx="12" cy="12" r="4"></circle><path d="M12 2v2M12 20v2M4.93 4.93l1.42 1.42M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.42-1.42M17.66 6.34l1.41-1.41"></path></svg>';const moon='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.8A8.5 8.5 0 1 1 11.2 3 6.7 6.7 0 0 0 21 12.8Z"></path></svg>';
    const themeBtn=document.createElement('button');themeBtn.id='themeToggle';themeBtn.type='button';themeBtn.setAttribute('aria-label','切换浅色模式');document.body.appendChild(themeBtn);const applyTheme=mode=>{const light=mode==='light';document.body.classList.toggle('light-theme',light);themeBtn.innerHTML=light?moon:sun;themeBtn.setAttribute('aria-label',light?'切换深色模式':'切换浅色模式');document.querySelector('meta[name="theme-color"]')?.setAttribute('content',light?'#f7f5ff':'#080b10')};const saved=localStorage.getItem('dreamcar-theme')||'dark';applyTheme(saved);themeBtn.addEventListener('click',()=>{const next=document.body.classList.contains('light-theme')?'dark':'light';localStorage.setItem('dreamcar-theme',next);applyTheme(next)});
    const status=document.querySelector('.hero .status');if(status&&!document.getElementById('statusActions')){const wrap=document.createElement('div');wrap.id='statusActions';status.parentNode.insertBefore(wrap,status);wrap.appendChild(status)}const wrap=document.getElementById('statusActions');if(wrap&&!document.getElementById('allCarsLink')){const link=document.createElement('a');link.id='allCarsLink';link.href='https://m.akd.cn/';link.target='_blank';link.rel='noopener noreferrer';link.setAttribute('aria-label','查看全部车源');link.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="7"></circle><path d="m20 20-4-4"></path></svg><span>查看全部车源</span>';wrap.insertBefore(link,status)}
    const scanSummary=document.getElementById('scanSummary');if(scanSummary){const clean=()=>{scanSummary.querySelectorAll('*').forEach(el=>{if(el.childNodes.length===1&&el.firstChild?.nodeType===3&&el.textContent.trim()==='当前结果')el.remove()});scanSummary.childNodes.forEach(n=>{if(n.nodeType===3)n.textContent=n.textContent.replace(/当前结果/g,'')})};new MutationObserver(clean).observe(scanSummary,{childList:true,subtree:true});clean()}
    if(form){const backdrop=document.createElement('div');backdrop.id='ruleModalBackdrop';document.body.appendChild(backdrop);const sync=()=>{const open=form.classList.contains('open');backdrop.classList.toggle('open',open);document.body.classList.toggle('rule-modal-open',open)};new MutationObserver(sync).observe(form,{attributes:true,attributeFilter:['class']});sync();backdrop.addEventListener('click',()=>document.getElementById('cancel')?.click());document.addEventListener('keydown',e=>{if(e.key==='Escape'&&form.classList.contains('open'))document.getElementById('cancel')?.click()})}
  });
})();